[tool.poetry]
name = "MoUSE"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.20.0"
matplotlib = "3.6.3"
opencv-python = "4.4.0.40"
pandas = "1.1.0"
scikit-image = "0.19.3"
scipy = "1.9.3"


[tool.flake8]
docstring-convention = "numpy"
ignore = "W, E, F, D104, D105"
max-line-length = 88
extend-ignore = "E203, W503"

[tool.yapf]
based_on_style = "google"
split_all_top_level_comma_separated_values = true
column_limit = 88

[tool.poetry.group.dev-tools.dependencies]
yapf = "0.40.2"
flake8 = "7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"