[tool.poetry]
name = "MoUSE"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
librosa = "^0.10"
torch = "^2.2"
torchaudio = "^2.2"
torchvision = "^0.17"
numpy = "^1.26"
matplotlib = "^3.8"
opencv-python = "^4.9.0"
pandas = "^2.2"
scikit-image = "^0.23"
scikit-learn = "^1.4"
scipy = "^1.13"
pytorch_lightning = "^2.2"
rtree = "^1.2"
protobuf3 = "^0.2"
bayesian-optimization = "^1.4"
seaborn = "^0.13"

[tool.poetry.dev-dependencies]
environ-config = "^23.2"
ray = "^2.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
