[tool.poetry]
name = "MoUSE"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.26.4"
matplotlib = "3.9.1"
opencv-python = "4.10.0.84"
pandas = "1.5.3"
scikit-image = "0.23.2"
scipy = "1.13.1"


[tool.flake8]
docstring-convention = "numpy"
ignore = "W, E, F, D104, D105"
max-line-length = 88
extend-ignore = "E203, W503"

[tool.yapf]
based_on_style = "google"
split_all_top_level_comma_separated_values = true
column_limit = 88

[tool.poetry.group.dev-tools.dependencies]
pytest = "8.3.2"
yapf = "0.40.2"
flake8 = "7.0.0"

[build-system]
requires = ["poetry-core"]