name: Code linter

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install
      - name: Run flake8
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run flake8 ./src
      - name: Run yapf
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          CHECK=$(poetry run yapf --diff --recursive ./src | grep ".*(reformatted)" | wc -l)
          if (($CHECK>0)); then exit 1; else exit 0; fi;
