name: Pytest tests

on:
  push:
    branches: [python3.11-adjustment]
  pull_request:
    branches: [python3.11-adjustment]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    env:
      POETRY_VIRTUALENVS_CREATE: false
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip and install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
          poetry update
      - name: Check Python version
        run: python --version
      - name: Run pytest
        run: pytest
